import { INestApplication } from '@nestjs/common';
import {
  DocumentBuilder,
  OpenAPIObject,
  SwaggerCustomOptions,
  SwaggerModule,
} from '@nestjs/swagger';
import * as fs from 'fs';
import * as path from 'path';

export const SwaggerConfig = (app: INestApplication) => {
  // Common useage of Swagger
  // const swaggerOptions = new DocumentBuilder()
  //   .setTitle('Swagger Docs')
  //   .setDescription('')
  //   .setVersion('1.0.0')
  //   .build();
  // const docs = SwaggerModule.createDocument(app, swaggerOptions);
  // SwaggerModule.setup('docs', app, docs);

  // Load swagger from existing (generated by nestia)
  const swaggerOptions = JSON.parse(
    fs.readFileSync(path.resolve(__dirname, '../../swagger.json'), 'utf8'),
  ) as OpenAPIObject;

  // Override server info
  swaggerOptions.servers[0].url = 'http://localhost:3000';
  swaggerOptions.servers[0].description = 'Localhost';

  SwaggerModule.setup('docs', app, swaggerOptions);
};
